// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArB4aWMCrRsc0icenwKo4l8zIm0s7yyE8',
    appId: '1:44943925642:web:f731d39db4b38947432873',
    messagingSenderId: '44943925642',
    projectId: 'my-flutt-app-140525',
    authDomain: 'my-flutt-app-140525.firebaseapp.com',
    storageBucket: 'my-flutt-app-140525.firebasestorage.app',
    measurementId: 'G-LBTDBTMK80',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr8msQupTCBzBOfgiDAq3GDskYaphGxVc',
    appId: '1:44943925642:android:5d90ebbd329ed081432873',
    messagingSenderId: '44943925642',
    projectId: 'my-flutt-app-140525',
    storageBucket: 'my-flutt-app-140525.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB198KcEPWpVjN0YLHzhLZjVaiMofsDark',
    appId: '1:44943925642:ios:ea6359896775cb74432873',
    messagingSenderId: '44943925642',
    projectId: 'my-flutt-app-140525',
    storageBucket: 'my-flutt-app-140525.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB198KcEPWpVjN0YLHzhLZjVaiMofsDark',
    appId: '1:44943925642:ios:ea6359896775cb74432873',
    messagingSenderId: '44943925642',
    projectId: 'my-flutt-app-140525',
    storageBucket: 'my-flutt-app-140525.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArB4aWMCrRsc0icenwKo4l8zIm0s7yyE8',
    appId: '1:44943925642:web:0aa20959579edd1d432873',
    messagingSenderId: '44943925642',
    projectId: 'my-flutt-app-140525',
    authDomain: 'my-flutt-app-140525.firebaseapp.com',
    storageBucket: 'my-flutt-app-140525.firebasestorage.app',
    measurementId: 'G-NJF0ZG4QXG',
  );

}